from distutils.core import setup
setup(
    name="WACA-Guard",
    version="4.0",
    py_modules=[
    "disnake",
    "other_dependency",
    "chat-exporter",
    "regex",
    "asyncio",
    "python-Levenshtein",
    "aiofiles",
    "numpy",
    "numba",
    "iris",
    "scikit-learn",
    "fuzzywuzzy",
    "SpeechRecognition",
    "Pydub",
    "sqlite3"
    ])
